### PR TITLE
Fixes zombie phantomjs processes

### PR DESCRIPTION
**Pull request by aaronrenner**
After running wallaby as part of a separate application, I confirmed we were still leaving around zombie phantom processes (see #224). It turns out if we kill the script's process group, it will kill all of the child processes as well. This appears to fix the zombie issue once and for all.

One thing to note, I kill the process group by using the negative value of the wrapper script's pid, instead of using `ps axo pid, pgid` to look up the process group id. This is because I was occasionally running into issues where the process group lookup wasn't returning a result, causing
more zombie processes. Hopefully this approach won't cause any issues.

I've tested this on OS X and ubuntu and don't see any processes being left alive. I'm definitely not a shell scripting master, so any ideas for improvement would be greatly appreciated.

### CODE REVIEW

**Comment by sanderhahn** [comment]
We also experienced zombie phantomjs processes, adding `on_exit fn -> Wallaby.end_session(session) end` in our `FeatureCase` setup block seemed to fix this. Not sure if this call is the correct way to fix it, because it is not documented in the readme.

```
    {:ok, session} = Wallaby.start_session(metadata: metadata)
    on_exit fn -> Wallaby.end_session(session) end
    {:ok, session: session}
```

**Comment by PragTob** [comment]
@sanderhahn hmm interesting... I thought sessions should be ended correctly but I'd have to check again

**Comment by keathley** [comment]
@sanderhahn Wallaby monitors each test process (the erlang process the test runs in) and closes the session when it gets a down signal. The code is here: https://github.com/keathley/wallaby/blob/master/lib/wallaby/session_store.ex

Adding the `on_exit` shouldn't cause an issue but if automatic session cleanup isn't working then its probably a separate bug.

**Comment by PragTob** [comment]
restarted the failing job... I think I gotta port over my wrapper from benchee finally...

```
Randomized with seed 369729
** (ExCoveralls.ReportUploadError) Failed to upload the report to 'https://coveralls.io' (reason: timeout).
    lib/excoveralls/poster.ex:20: ExCoveralls.Poster.execute/2
    (mix) lib/mix/tasks/test.ex:245: Mix.Tasks.Test.run/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    lib/mix/tasks.ex:51: Mix.Tasks.Coveralls.do_run/2
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
The command "mix coveralls.travis" exited with 1.
0.00s$ if [ -z ${WALLABY_DRIVER} ]; then mix dialyzer --halt-exit-status; fi
```

**Comment by sparta-developers** [comment]
FYI these changes fix the zombie phantomjs problem for us, as well. We just noticed that we had >2000 phantomjs processes on one of our workstations. Yikes!

**Comment by keathley** [comment]
I'll merge this and push out a new point release.

**Comment by tmecklem** [comment]
Sorry to bump this, but I'm encountering this too. Can I somehow entice you to do a release with this fix, @keathley?

**Comment by keathley** [comment]
@tmecklem Sorry about that. Version 0.20 has just been pushed.

**Pull request merged**
