### PR TITLE
runs chromedriver without a sandbox

### PR DESCRIPTION
**Pull request by StefanoDeVuono**
On newer versions of MacOS, running wallaby with chromedriver causes the following warning:

`chromedriver[nnnn:nnnnnn] pid(nnn)/euid(nnn) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!`

Over and over again. On apple.com forums, I found that this is related to [key events being sent to a secondary thread](https://forums.developer.apple.com/thread/105244).

I noticed that for karma-chrome-launcher, the `--no-sandbox` flag [seems to help](https://github.com/karma-runner/karma-chrome-launcher/issues/189) [in headless](https://github.com/karma-runner/karma-chrome-launcher/issues/146) [mode](https://github.com/karma-runner/karma-chrome-launcher/issues/137).

So, I'm submitting a PR to run chromedriver in headless mode by default with wallaby as well.

### CODE REVIEW

**Comment by StefanoDeVuono** [comment]
@mhanberg Ostensibly, yes. But I'm running wallaby 0.20.0 and still getting those errors.

**Comment by keathley** [comment]
@StefanoDeVuono Thanks for the fix! This all LGTM. I'm curious if this was happening even on master or if the port change fixed it. Either way not opposed to this fix. Just curious.

**Comment by StefanoDeVuono** [comment]
I saw it on 0.13.0 and 0.20.0. In your experience, the port change alone did the trick?

**Comment by keathley** [comment]
I think the port change is only on master. That doesn't mean that we shouldn't be using this though. I'm not sure what else the --no-sandbox flag changes for chromedriver.

**Comment by StefanoDeVuono** [comment]
@keathley Oh. Wouldn't putting version 0.20.0 is my `mix.exs` file use the master branch version of wallaby?

**Comment by keathley** [comment]
Ah! No it'll just pull the 0.20 tag from hex. You can try running it locally in order to see if it still outputs all the noise.

**Comment by StefanoDeVuono** [comment]
@keathley Whoa! How do I get the updated version in my mix file?

Lemme take a look. Maybe this PR is for naught!

Thanks for your help, btw

**Comment by keathley** [comment]
You can try swapping out the `"~> 0.20"` with something like `git: "https://github.com/keathley/wallaby.git"`. I forget the exact magical incantation for that but its probably pretty close. The info is here: https://hexdocs.pm/mix/Mix.Tasks.Deps.html.

**Comment by StefanoDeVuono** [comment]
@keathley Yeah. I saw that. I'm new to elixir and I just assumed that updating the version number would download that version. Good to know!

Also, it works with `{:wallaby, github: "keathley/wallaby", only: :test}`

Thanks again. I'm closing this out.

**Comment by keathley** [comment]
No prob. Welcome to the community :smile:

**Comment by StefanoDeVuono** [comment]
Oh, also, I noticed that version 0.20.0 came out around 11 April and [PR 376](https://github.com/keathley/wallaby/pull/376) around 10 July

Two questions:
1. Would you accept a PR bumping wallaby to say 0.20.1 or 0.21.0?
1. Would putting that version in my mix.exs file get hex to download the current master once the version change PR is merged in?

**Comment by keathley** [comment]
We'll have to bump the version. I'll make sure that we don't have any breaking changes in this release and see if I can push a new version to hex :+1:

**Pull request closed without merging**
