### PR TITLE
Run against Erlang 19.3 & 18.3

### PR DESCRIPTION
**Pull request by PragTob**
* also found out there is an erlang 18.3.4 which we can run against
* made it a proper crossover matrix with all elixir versions against
  all erlang versions - thank you travis sorry for the load :)

### CODE REVIEW

**Comment by PragTob** [comment]
Dialyzer throws warnings/errors on the combination of elixir 1.4.2 and Erlang 18.3 - funnily I have a similiar problem over at benchee but with Erlang 18.2 I suppose.

```
lib/wallaby/browser.ex:795: The call _@2:'conditions'() requires that _@2 is of type atom() | tuple() not #{}

lib/wallaby/browser.ex:980: The call _@1:'host'() requires that _@1 is of type atom() | tuple() not #{}

lib/wallaby/browser.ex:982: The call _@4:'host'() requires that _@4 is of type atom() | tuple() not #{}

lib/wallaby/browser.ex:1121: The call _@1:'selector'() requires that _@1 is of type atom() | tuple() not #{}

lib/wallaby/browser.ex:1131: The call _@1:'selector'() requires that _@1 is of type atom() | tuple() not #{}

lib/wallaby/phantom/driver.ex:317: The call _@1:'session_url'() requires that _@1 is of type atom() | tuple() not #{}

lib/wallaby/phantom/server.ex:93: The call _@4:'base_url'() requires that _@4 is of type atom() | tuple() not #{}

lib/wallaby/phantom/server.ex:93: The call _@2:'awaiting_url'() requires that _@2 is of type atom() | tuple() not #{}

lib/wallaby/phantom/server.ex:109: The call _@1:'awaiting_url'() requires that _@1 is of type atom() | tuple() not #{}

lib/wallaby/query.ex:245: The call _@1:'result'() requires that _@1 is of type atom() | tuple() not #{}

lib/wallaby/query.ex:248: The call _@2:'result'() requires that _@2 is of type atom() | tuple() not #{}

lib/wallaby/query/error_message.ex:63: The call _@19:'result'() requires that _@19 is of type atom() | tuple() not #{}

lib/wallaby/query/error_message.ex:63: The call _@16:'result'() requires that _@16 is of type atom() | tuple() not #{}

lib/wallaby/query/error_message.ex:63: The call _@15:'method'() requires that _@15 is of type atom() | tuple() not #{}

lib/wallaby/query/error_message.ex:63: The call _@10:'result'() requires that _@10 is of type atom() | tuple() not #{}

lib/wallaby/query/error_message.ex:63: The call _@7:'selector'() requires that _@7 is of type atom() | tuple() not #{}

lib/wallaby/query/error_message.ex:75: The call _@1:'method'() requires that _@1 is of type atom() | tuple() not #{}

lib/wallaby/query/error_message.ex:162: The call _@1:'conditions'() requires that _@1 is of type atom() | tuple() not #{}

lib/wallaby/query/error_message.ex:168: The call _@6:'result'() requires that _@6 is of type atom() | tuple() not #{}

lib/wallaby/query/error_message.ex:171: The call _@11:'result'() requires that _@11 is of type atom() | tuple() not #{}
```

I try to solve it through more typespecs/structs over at benchee but that's just a guess.

@aaronrenner - any idea, you seem to know this stuff? :D

**Comment by aaronrenner** [comment]
@PragTob I played around with the combination of Elixir 1.4.2 and Erlang 18.3 and I'm not having any luck either. Since the rest of the matrix passes, can we just exclude that combination?

I also just checked in some big build changes as a part of #198. What do you think about updating the Elixir and Erlang versions after that commit is merged?

**Comment by PragTob** [comment]
If it makes your life easier, let's hold this merge until #198 is in to avoid merge conflicts on that big PR, they are easier to resolve over here :+1:

Regarding the exclusion, I might open an issue at elixir lang as it seems curious. I'll see if I can just skip the dialyzer part instead of the whole build

**Comment by aaronrenner** [comment]
I would be really interested to hear the response if you open an issue at elixir lang too. Would you add a link to the issue here for posterity?

**Comment by PragTob** [comment]
When I open the issue I link to both this here and my benchee PR :) I'll finish my work on a theory how to get it away on benchee and then hopefully get to it :)

**Comment by PragTob** [comment]
^ Issue is there for the interested :) Yes, I'm bad at distilling it down to shorter titles.

**Comment by PragTob** [comment]
I just claim that this is good to go now.

**Pull request merged**
