### PR TITLE
Execute script async

### PR DESCRIPTION
**Pull request by daveed-al**
Adding async functionality to executing javascript.

### CODE REVIEW

**Comment by carl-al** [comment]
@aaronrenner @keathley @PragTob 

Hey Guys, we would love to contribute here, but with the lack of responses or communication this is difficult, we would like to engage a dialogue on the topic of async testing on Selenium v2.

How would you like us to proceed? 

Carl

**Comment by keathley** [comment]
This code looks good to me. I'm not sure what to do about the selenium 2 issue. Is there any way for us to specify the script timeout default?

**Comment by keathley** [comment]
@carl-al I've been talking with @aaronrenner and he thinks that we may need to continue to support selenium 2 in order to test with older firefox versions. Still working on confirming that. In the meantime take a look at https://www.w3.org/TR/webdriver/#dfn-timeouts. I think we may be able to use that to increase the timeouts for script execution.

**Comment by keathley** [comment]
@carl-al Have you tried adding the timeouts to the default capabilities for selenium? Something like this:

```elixir
defp default_capabilities do
  %{
    javascriptEnabled: true,
    timeouts: %{
      script: "30000",
    },
  }
end
```

**Comment by michallepicki** [comment]
@daveed-al Could you please rebase on master?
I'm working with Selenium recently, I can review this PR over the weekend.

**Comment by michallepicki** [comment]
Closing in favor of #445

**Pull request closed without merging**
