### PR TITLE
Update .travis.yaml to include the 3 latest elixir versions

### PR DESCRIPTION
**Pull request by saulecabrera**
This PR solves #410 

Just followed the previous convention and added the 3 latest versions.

### CODE REVIEW

**Comment by saulecabrera** [comment]
Also, should I update `.tool-versions` to match any of the versions that we are testing against?

**Comment by keathley** [comment]
Looks like we've got some issues with deprecation warnings in newer versions of elixir. Need to see if we can safely solve those and still support older versions of the language.

**Comment by saulecabrera** [comment]
Right, I just checked the logs for the builds and the warning relies on the usage of `super` for `handle_info/2` and `terminate/2` in the following files: 
- https://github.com/keathley/wallaby/blob/master/lib/wallaby/driver/process_workspace/server.ex
- https://github.com/keathley/wallaby/blob/master/lib/wallaby/phantom/server.ex#L88

This deprecation was introduced in elixir 1.7 https://github.com/elixir-lang/elixir/blob/v1.7/CHANGELOG.md#elixir-7

Since these are GenServer overridables, if we wanted to be explicit we could return the default implementation for each:
- `{:noreply, state}` for `handle_info/2`
- `:ok` for `terminate/2`

I pushed the changes which I tested locally, let me know if they make sense.

**Comment by keathley** [comment]
That all makes sense to me. Thanks for making those changes @saulecabrera!

**Pull request merged**
