### PR TITLE
Configure chromedriver path

### PR DESCRIPTION
**Pull request by jfornoff**
Allow for Chromedriver binary to be specified by
```
config :wallaby, chromedriver: "<my/path/to/chromedriver>"
```

Any feedback very welcome :-)

### CODE REVIEW

**Comment by keathley** [comment]
Ugh, sorry @jfornoff looks like you have some credo checks failing. I'm going to revise our list of checks soon so we have less of these issues but if you don't mind fixing them for now I can get this merged ASAP :).

**Comment by jfornoff** [comment]
Whoa my bad :) I didn't check on the build status. Should be fine now!

**Comment by jfornoff** [comment]
Ping @keathley :-)

**Comment by jfornoff** [comment]
🎉 thx @mhanberg, could we potentially also shoot a Hex release?

**Comment by michallepicki** [comment]
Hmm we should bump ex_doc before to get the versions dropdown on hex, I'll make a PR

**Comment by jfornoff** [comment]
@michallepicki #426 good to merge?

**Pull request merged**
