### PR TITLE
Separate local storage per phantom

### PR DESCRIPTION
**Pull request by whw**
To better isolate tests, I thought it would be a good idea for each PhantomJS process to have its own local storage directory.

### CODE REVIEW

**Comment by aaronjensen** [comment]
@keathley Is this good to go? We're using this and it's a necessary thing if you want to support local storage and multiple threads.

**Comment by keathley** [comment]
Yup this looks good to me. Thanks @whw! :tada:

**Comment by keathley** [comment]
@aaronjensen Just cut a new release with these fixes. Lemme know if you have any issues with it.

**Comment by aaronjensen** [comment]
That's great, thank you @keathley

**Pull request merged**
