### PR TITLE
Fill in with Emoji test

### PR DESCRIPTION
**Pull request by keathley**
## DO NOT MERGE

This reproduces the issue in #346. I'm not sure exactly how we should fix this yet and wanted to get some insight. [Gitlab experienced this same issue](https://about.gitlab.com/2017/12/19/moving-to-headless-chrome) and worked around it by filling in the field with js. Should we consider going that same route?

### CODE REVIEW

**Comment by keathley** [comment]
Well, we have to actual do the ~~annoying~~ fun work of fixing it 😝.

**Comment by PragTob** [comment]
easy peasy... ;P

**Comment by mhanberg** [comment]
This appears to be a [chromedriver problem](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2269) and not a Wallaby problem.

I propose that the solution should be to document the behavior and potential workarounds, but not implement any special cases.

@michallepicki What do you think?

**Comment by michallepicki** [comment]
@mhanberg It's awesome that you found the issue tracked in chromedriver!

I agree with @keathley 's comment from here: https://github.com/keathley/wallaby/issues/346#issuecomment-404176302

I think we should document this behavior, link to the chromedriver issue and close this PR. But I think this should be documented here instead of the README, we should clean up the README instead of adding things to it: https://hexdocs.pm/wallaby/Wallaby.Browser.html#fill_in/3

**Pull request closed without merging**
