### PR TITLE
Option to configure default window size

### PR DESCRIPTION
**Pull request by mhanberg**
Addresses #152 

@keathley @PragTob @aaronrenner Let me know what you think.

Thanks!

### CODE REVIEW

**Comment by mhanberg** [comment]
One test failure is for `travis.coveralls`, the others I'm not so sure about. 

I wasn't able to run all of the selenium tests locally. Most were failing with something like this

```
Cannot find function clause

defp something(%{"element-235h3kj45h3k4h523j45" => "something})

did you mea

defp something(%{"ELEMENT" => "something
```

so I'm not sure if the travis errors are legitimate or not.

**Comment by keathley** [comment]
@mhanberg Thanks! Let me take a look at the test failures.

**Comment by keathley** [comment]
This code looks good to me. @mhanberg I merged your PR for returning the correct errors from http calls. If you want to rebase this branch against master then we can see what the real error is. Its happening on test runs for other branches as well so its either that something is broken on master or broken in our CI or something.

**Comment by mhanberg** [comment]
I rebased and it looks like the same results (except with an extra `travis.coveralls` failure).

The test failures are all with `WALLABY_SELENIUM_VERSION=3`, so I'm guessing it has something to do with that. Is that configured to be a specific version of selenium, or could it have been changed silently? (meaning something like `latest` instead of `1.1.1`)

**Comment by keathley** [comment]
Looks like we're using an explicit version of selenium: https://github.com/keathley/wallaby/blob/master/test/tools/start_webdriver.sh#L15 and ghecko driver but "latest" version of firefox: https://github.com/keathley/wallaby/blob/master/test/tools/start_webdriver.sh#L30.

I suspect that this might be the issue.

**Comment by keathley** [comment]
Just checked and it looks like the most recent version of selenium is 3.14 and most recent version of ghecko driver is 0.23. @mhanberg if you wanna submit a separate PR for those fixes to see if they fix the problem that would be great. Otherwise it'll be a bit before I can get around to it.

**Comment by mhanberg** [comment]
@keathley I can take care of that. Thanks for digging into it :the

**Comment by mhanberg** [comment]
@keathley we're green on Travis now thanks to the other PR's 👍

**Comment by keathley** [comment]
Thanks @mhanberg :tada:

**Pull request merged**
