### PR TITLE
Add support for chrome binary option

### PR DESCRIPTION
**Pull request by opsb**
Continued from https://github.com/keathley/wallaby/pull/309#discussion_r140837822 (PR from different fork).

Requests from previous PR
- [x] this is totally nitpicking and not sure if others agree, but I'd implement this using 2 methods and pattern matching on nil in the first clause :)
- [x] Can we change the wording of this to just "but if you want to test against a different version..."
- [x] Can this function be private? 
- [x] credo warning (required update to 0.8.10 due to https://github.com/rrrene/credo/issues/469)
- [ ] Switch to `config :wallaby, Wallaby.Experimental.Chrome` convention (going to leave for this PR as it's an existing convention on the project)

### CODE REVIEW

**Comment by opsb** [comment]
@keathley @PragTob not sure what the issue is with the build there, looks spurious, I suspect a rebuild would fix it.

**Comment by PragTob** [comment]
@opsb rebuilds triggered... not sure why that part now likes to misbehave

**Comment by keathley** [comment]
I'm gunna open an issue about fixing our CI builds. They're almost more trouble then they're worth atm.

**Comment by keathley** [comment]
The failures on CI look isolated to chrome. This might have included a regression somewhere.

**Comment by keathley** [comment]
@opsb I've fixed the chrome issues in master. If you wouldn't mind rebasing your branch I'll get this merged.

**Comment by keathley** [comment]
Since this was really only blocked on the mix.lock conflict I cherry picked the important commit and went ahead and merged: https://github.com/keathley/wallaby/commit/4b444350ecc22ce451ef7a379ac2e4a6b8a071b8.

Thanks so much for working on this :tada:

**Pull request closed without merging**
