### PR TITLE
note about location/file type of AcceptanceCase

### PR DESCRIPTION
**Pull request by Ch4s3**

### CODE REVIEW

**Comment by Ch4s3** [comment]
@keathley ping

**Comment by PragTob** [comment]
Not sure, it needs the `note` as the sample path already says `.ex` and if you are in a Phoenix project already there's also model_case/conn_case and friends lying around there :)

**Comment by keathley** [comment]
I think I agree with @PragTob. I'm not sure that we need to explicitly state this. Really, I would rather automate the generation of an `acceptance_case.ex` for people so we can simply avoid these types of issues. I'm going to close this for now. @Ch4s3 if you wanna help with automating this task via. a mix task let me know and we can discuss how that might be implemented.

**Comment by Ch4s3** [comment]
I'm a little fuzzy about why I wanted this in the readme. I'll take a look at automating it.

**Pull request closed without merging**
