### PR TITLE
New feature: Support for Selecting an Option from a Select Box

### PR DESCRIPTION
**Pull request by eiseneker**
It's all in the name! Ask @bomatson or I if any questions.

### CODE REVIEW

**Comment by keathley** [comment]
Thanks for adding this!

I was wondering about the merits of the `from: ` option. Does it make sense to use that in this context? Or does it make more sense to just pass in the select box as the first option to the select? That would keep more in line with our existing semantics and would allow you to compose finders with selections for nesting purposes. I'm thinking of something like this:

```elixir
page
|> find(".signup-form")
|> select("Home State", option: "Florida")
```
or
``` elixir
page
|> find(".signup-form")
|> find(".home_state_field")
|> select(option: "Florida")
```

The `option` key might be unneeded here but it matches semantically with `fill_in(some_selector, with: foo)`.

What do you think about this?

**Comment by bomatson** [comment]
For sure! We were trying to emulate the behavior of `fill_in` as much as we could. We'll refactor this to match more closely with:

```
page
|> find(".signup-form")
|> select("Home State", option: "Massachusetts")
```

Does that work?

**Comment by keathley** [comment]
Sounds good to me.

**Comment by keathley** [comment]
This looks great! :tada:

**Pull request merged**
