### PR TITLE
Include HTTPoison errors in Wallaby error message when request fails.

### PR DESCRIPTION
**Pull request by eahanson**
To make it a little easier to track down issues.

### CODE REVIEW

**Comment by keathley** [comment]
Hey @eahanson this looks great. Looks like there's a dialyzer issue. If you can take care of that we can get this merged :+1:

**Comment by eahanson** [comment]
Travis timed out while uploading a build artifact. I'm going to close and then re-open this PR to trigger a new build.

**Comment by eahanson** [comment]
Hi @keathley I fixed the dialyzer issue!

**Comment by keathley** [comment]
Thanks @eahanson :tada:

**Pull request merged**
