### PR TITLE
Elixir 1.5.0 rc2 try

### PR DESCRIPTION
**Pull request by PragTob**
(will most likely fail, see if we can fix it otherwise tell the good folks at elixir)

### CODE REVIEW

**Comment by PragTob** [comment]
Woopsie:

```
.** (ExUnit.DuplicateDescribeError) describe "find/3" is already defined in Wallaby.Integration.Browser.FindTest

    integration_test/cases/browser/find_test.exs:130: (module)

    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

    (elixir) lib/code.ex:376: Code.require_file/2

    integration_test/chrome/all_test.exs:15: (file)

    (elixir) lib/code.ex:376: Code.require_file/2

    (elixir) lib/kernel/parallel_require.ex:59: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5

07:34:18.887 [error] GenServer #PID<0.263.0> terminating

** (ExUnit.DuplicateDescribeError) describe "find/3" is already defined in Wallaby.Integration.Browser.FindTest

    integration_test/cases/browser/find_test.exs:130: (module)

    (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
```

**Comment by keathley** [comment]
That...is a very interesting error. Not sure what changed in the compiler to start throwing those warnings.

**Comment by PragTob** [comment]
I guess they just made duplicated `describe` fail like it is with `test` which makes sense but can't find it in the changelog.

**Comment by keathley** [comment]
Interesting about the duplicate `describe` block. I guess that ends up being helpful if you use the descriptions to find tests. I typically just use line numbers which is probably why I missed it 😈

**Comment by PragTob** [comment]
Ah finally green... on to the merge!

**Pull request merged**
